# Generated by Django 4.2.7 on 2023-11-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_serviceprovider_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='spframe',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.serviceprovider'),
        ),
    ]
