# Generated by Django 4.2.7 on 2023-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_spframe_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spframe',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spframe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
