# Generated by Django 4.2.7 on 2023-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_serviceprovider_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwaitingtime',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerwaitingtime',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spframe',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
