# Generated by Django 4.2.7 on 2023-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_customerwaitingtime_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spframe',
            name='head_coordinate',
            field=models.TextField(),
        ),
    ]
