# Generated by Django 4.2.7 on 2023-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_serviceserviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwaitingtime',
            name='updatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerwaitingtime',
            name='last_updated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerwaitingtime',
            name='start_date',
            field=models.IntegerField(null=True),
        ),
    ]
